name: Deploy Node Application

on:
  push:
    branches:
      - master
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: cd server && docker build -t isuruk1/realist-server  .
      - name: Publish Image to docker hub
        run: docker push isuruk1/realist-server

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull isuruk1/realist-server
      - name: Delete old container
        run: docker rm -f realist-server-container
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name realist-server-container -e DATABASE='${{ secrets.DATABASE }}' -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' -e EMAIL_FROM='${{ secrets.EMAIL_FROM }}' -e REPLY_TO='${{ secrets.REPLY_TO }}' -e JWT_SECRET='${{ secrets.JWT_SECRET }}' -e CLIENT_URL='${{ secrets.CLIENT_URL }}' -e AWS_BUCKET='${{ secrets.AWS_BUCKET }}' -e GOOGLE_API_KEY='${{ secrets.GOOGLE_API_KEY }}' isuruk1/realist-server
